title: My Corner of The Web
author: Eric Sparks 
email: SparksEric90@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This is just my small corner of the web. I'll talk about 3D Printing mostly.
  Everything from maintaining your printer, to different types of filament, all the
  way to printer reviews.

# social links
twitter_username: yudream4 # DO NOT include the @ character, or else the build will fail!
github_username:  sparkseric90 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
